### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by malicious-dev** [Upbolt/Hydroxide#102]
![Screenshot 2023-08-16 084752](https://github.com/Upbolt/Hydroxide/assets/46420533/9a5d7cf6-4562-4831-8a49-9c47c7149086)

**Comment by ghost** [comment]
what executor are you using, I can't even manage to get hydroxide to load without it crashing my roblox for some reason

**Comment by malicious-dev** [comment]
Shadow, Valyse, Prime

**Comment by jwuhlie** [comment]
I'm having the same issue.

**Comment by Kyurem102** [comment]
Yep, crashing upon execution on Electron

**Comment by sdhhf1245** [comment]
crashing upon valyse and fluxus

**Comment by Upbolt** [comment]
upstream issue, hydroxide worked fine with pre-hyperion executors
