### ISSUE TITLE
use or getInfo(upvalue).namewhat to support protosmasher

### ISSUE THREAD

**Issue by Hynec** [Upbolt/Hydroxide#11]
https://github.com/Upbolt/Hydroxide/blob/2352a85b76616a95468b1f3629d54ae620778863/modules/UpvalueScanner.lua#L28

use or getInfo(upvalue).namewhat to support protosmasher

**Comment by Upbolt** [comment]
`getInfo(value).name or ''`

**Comment by Hynec** [comment]
ok cool.
