### ISSUE TITLE
Use Disassembler in Script-Ware instead of Decompiler

### ISSUE THREAD

**Issue by Exponential-Workload** [Upbolt/Hydroxide#63]
SW's decompiler has been unavailable for a while now, so I'd suggest using it's [Disassembler](https://docs.script-ware.com/script-disassembler) (use basic feature detection or [`getexecutorname and getexecutorname() === 'ScriptWare'`](https://docs.script-ware.com/script-ware-functions#qx-get-executor-name)) instead of the currently still unavailable decompiler, once someone implements the text box.

**Comment by Upbolt** [comment]
not planned for this iteration of hydroxide
