### ISSUE TITLE
conditional logging doesn't seem to work

### ISSUE THREAD

**Issue by AmongBrapFard** [Upbolt/Hydroxide#72]
the remotespy conditional logging doesn't seem to be working, unless im using it wrong. can someone try to use this

**Comment by Upbolt** [comment]
I don't think I've gotten any other complaints with this issue, so you're probably not using it correctly. Make sure values, types. and the arg index are correct, and also be aware of hidden white-space characters within strings if you're trying to ignore those. No current plan to provide a solution to that unfortunately, but if it becomes a big enough problem I might reconsider.
