### ISSUE TITLE
UI layers on-top of itself when scrolling down a long list

### ISSUE THREAD

**Issue by hl2jeep** [Upbolt/Hydroxide#81]
to explain in simple terms, when i have a long list of upvalues, at a certain point when scrolling down, the UI elements start stacking on top of eachother, making the interface very hard to use. i can't show an image right now because roblox just updated, will attach one as soon as i can

**Comment by sans-undertae** [comment]
its a roblox issue with uilistlayouts; not really possible to fix without a big rework of the scrolling lists

**Comment by Upbolt** [comment]
> its a roblox issue with the UIGridStyleLayout class; not really possible to fix without a big rework of the scrolling lists

unfortunately, this ^
