### ISSUE TITLE
hydroxide refuses to work (im on synapse v2)

### ISSUE THREAD

**Issue by intestines83** [Upbolt/Hydroxide#84]
it takes about 5 tries to get it to load and when it does none of the buttons on the left work so i cant do anything with it usually gives these errors
![errors](https://user-images.githubusercontent.com/108042717/204719663-ffb1f65c-3762-45fe-9e52-7bb3aa0d4a3c.png)

**Comment by Blessedsolaris** [comment]
The loadstring is wrong.

**Comment by Blessedsolaris** [comment]
the %s's need to be replaced by the owner.

**Comment by Upbolt** [comment]
roblox api desync
