### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by Blessedsolaris** [Upbolt/Hydroxide#87]

**Comment by Blessedsolaris** [comment]
or fixed my bad

**Comment by Blessedsolaris** [comment]
local owner = "Upbolt"
local branch = "revision"

local function webImport(file)
    return loadstring(game:HttpGetAsync(("https://github.com/Upbolt/Hydroxide/blob/revision/init.lua"):format(owner, branch, file)), file .. '.lua')()
end

webImport("init")
webImport("ui/main")

**Comment by Blessedsolaris** [comment]
that should be the fixed code.

**Comment by Blessedsolaris** [comment]
the current webimport function also doesnt work.

**Comment by sans-undertae** [comment]
what are you talking about? do you mean the %s 's in `https://raw.githubusercontent.com/%s/Hydroxide/%s/%s.lua`?
those are intentional, its how `string.format` works

**Comment by ImInTheICU** [comment]
idk but generally speaking his tool sucks ass.

**Comment by Blessedsolaris** [comment]
well the current code seemed to have typos since it wont execute at all.
