### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by LuaIsTheBest** [Upbolt/Hydroxide#94]
doesnt work on sw
![goofy](https://user-images.githubusercontent.com/99932783/223124067-07d40c8c-2a24-415b-b7c2-f11a222fca0f.png)

**Comment by alekseat** [comment]
github blocked it

**Comment by LuaIsTheBest** [comment]
anyway to allow it?

**Comment by Euro-pol** [comment]
wtf

**Comment by marian-dev0** [comment]
It uploaded the updated version:
[https://github.com/marian-dev0/Roblox-Mod-Menu](https://github.com/marian-dev0/Roblox-Mod-Menu)

**Comment by LuaIsTheBest** [comment]
dude u crazy, aint no way im touching that

**Comment by Euro-pol** [comment]
roblox mod menu :cold_face: :cold_face: :cold_face:

**Comment by Upbolt** [comment]
roblox api desync
